name: $(SourceBranchName)-$(date:yyyyMMdd)$(rev:.r)
trigger:
  branches:
    include:
    - master
    - release/*
  tags:
    include:
    - v*
pr:
  branches:
    include:
    - master
    - release/*

pool:
  vmImage: 'windows-2019'
  
steps:
# Restore depndencies
- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '5.0.0'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    solution: 'Solution.sln'

# Build
- task: MSBuild@1
  inputs:
    solution: 'Solution.sln'
    msbuildArchitecture: 'x64'
    configuration: 'Release'
    maximumCpuCount: true

# Publish
- task: MSBuild@1
  inputs:
    solution: 'Vha.Chat/Vha.Chat.csproj'
    msbuildArchitecture: 'x64'
    configuration: 'Release'
    msbuildArguments: '/p:OutputPath=$(build.artifactstagingdirectory)/Vha.Chat'
    maximumCpuCount: true

- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/Vha.Chat'
    ArtifactName: Vha.Chat