name: $(SourceBranchName)-$(date:yyyyMMdd)$(rev:.r)
trigger:
  branches:
    include:
    - master
    - release/*
  tags:
    include:
    - v*
pr:
  branches:
    include:
    - master
    - release/*

pool:
  vmImage: 'windows-2019'
  
steps:
# Build
- task: MSBuild@1
  inputs:
    solution: 'Vha.Chat/Vha.Chat.csproj'
    msbuildArchitecture: 'x64'
    configuration: 'Release'
    msbuildArguments: '/p:OutputPath=$(build.artifactstagingdirectory)/Vha.Chat'
    maximumCpuCount: true
    restoreNugetPackages: true

# Publish
- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/Vha.Chat'
    ArtifactName: Vha.Chat