//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vha.Chat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vha.Chat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AboutBitmap {
            get {
                object obj = ResourceManager.GetObject("AboutBitmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrowserBitmap {
            get {
                object obj = ResourceManager.GetObject("BrowserBitmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon BrowserIcon {
            get {
                object obj = ResourceManager.GetObject("BrowserIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChannelBitmap {
            get {
                object obj = ResourceManager.GetObject("ChannelBitmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChannelDisabledBitmap {
            get {
                object obj = ResourceManager.GetObject("ChannelDisabledBitmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CharacterBitmap {
            get {
                object obj = ResourceManager.GetObject("CharacterBitmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CharacterOfflineBitmap {
            get {
                object obj = ResourceManager.GetObject("CharacterOfflineBitmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CharacterOnlineBitmap {
            get {
                object obj = ResourceManager.GetObject("CharacterOnlineBitmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CharactersBitmap {
            get {
                object obj = ResourceManager.GetObject("CharactersBitmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv = &quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///    body {
        ///        font-family: verdana, helvetica, sans-serif;
        ///	    font-size: 11px;
        ///	    padding: 0px 3px 0px 1px;
        ///	    margin: 0px;
        ///    }
        ///    .Line {
        ///        margin-left: 10px;
        ///    }
        ///    .Time {
        ///        margin-left: -10px;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ChatBigBitmap {
            get {
                object obj = ResourceManager.GetObject("ChatBigBitmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChatBitmap {
            get {
                object obj = ResourceManager.GetObject("ChatBitmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon ChatIcon {
            get {
                object obj = ResourceManager.GetObject("ChatIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConnectBitmap {
            get {
                object obj = ResourceManager.GetObject("ConnectBitmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeleteBitmap {
            get {
                object obj = ResourceManager.GetObject("DeleteBitmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DisconnectBitmap {
            get {
                object obj = ResourceManager.GetObject("DisconnectBitmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EnterBitmap {
            get {
                object obj = ResourceManager.GetObject("EnterBitmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeaveBitmap {
            get {
                object obj = ResourceManager.GetObject("LeaveBitmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OptionsBigBitmap {
            get {
                object obj = ResourceManager.GetObject("OptionsBigBitmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OptionsBitmap {
            get {
                object obj = ResourceManager.GetObject("OptionsBitmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon OptionsIcon {
            get {
                object obj = ResourceManager.GetObject("OptionsIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TalkBitmap {
            get {
                object obj = ResourceManager.GetObject("TalkBitmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
