//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vha.AOML.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vha.AOML.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;&lt;Root&gt;
        ///    &lt;!-- Named colours --&gt;
        ///    &lt;HTMLColor color=&quot;0x000000&quot; name=&quot;black&quot;/&gt;
        ///    &lt;HTMLColor color=&quot;0x008000&quot; name=&quot;green&quot;/&gt;
        ///    &lt;HTMLColor color=&quot;0xC0C0C0&quot; name=&quot;silver&quot;/&gt;
        ///    &lt;HTMLColor color=&quot;0x00FF00&quot; name=&quot;lime&quot;/&gt;
        ///    &lt;HTMLColor color=&quot;0x808080&quot; name=&quot;gray&quot;/&gt;
        ///    &lt;HTMLColor color=&quot;0x808000&quot; name=&quot;olive&quot;/&gt;
        ///    &lt;HTMLColor color=&quot;0xFFFFFF&quot; name=&quot;white&quot;/&gt;
        ///    &lt;HTMLColor color=&quot;0xFFFF00&quot; name=&quot;yellow&quot;/&gt;
        ///    &lt;HTMLColor color=&quot;0x800000&quot; name=&quot;maroon&quot;/&gt;
        ///    &lt;HTMLColor color= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextColors {
            get {
                return ResourceManager.GetString("TextColors", resourceCulture);
            }
        }
    }
}
