steps:
- powershell: |
    Write-Host "##vso[task.setvariable variable=DOTNET_SKIP_FIRST_TIME_EXPERIENCE;]true"
    Write-Host "##vso[task.setvariable variable=DOTNET_CLI_TELEMETRY_OPTOUT;]1"
  displayName: 'Opt-Out of .NET Core telemetry'

- task: NuGetToolInstaller@0
  displayName: 'Install NuGet 5.x'
  inputs:
    versionSpec: '5.x'

- task: DotNetCoreInstaller@0
  displayName: Install .NET Core SDK 	2.2.105
  inputs:
    packageType: sdk
    version: 	2.2.105

- script: dotnet --info
  displayName: Show .NET Core info
